"""initial

Revision ID: 20260821_0001
Revises:
Create Date: 2026-08-21 08:18:30.505374
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "20260821_0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "frameworks",
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=240), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_frameworks")),
        sa.UniqueConstraint("slug", name=op.f("uq_frameworks_slug")),
    )
    op.create_table(
        "workspaces",
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=240), nullable=False),
        sa.Column("timezone", sa.String(length=80), nullable=False),
        sa.Column("locale", sa.String(length=40), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspaces")),
        sa.UniqueConstraint("slug", name=op.f("uq_workspaces_slug")),
    )
    op.create_table(
        "framework_versions",
        sa.Column("framework_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.String(length=120), nullable=False),
        sa.Column("source_uri", sa.String(length=1000), nullable=False),
        sa.Column("source_hash", sa.String(length=64), nullable=False),
        sa.Column("verified_on", sa.Date(), nullable=False),
        sa.Column("published_at", sa.Date(), nullable=True),
        sa.Column("disclaimer", sa.Text(), nullable=False),
        sa.Column("imported_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["framework_id"],
            ["frameworks.id"],
            name=op.f("fk_framework_versions_framework_id_frameworks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_framework_versions")),
        sa.UniqueConstraint(
            "framework_id", "version", name="uq_framework_version_framework_version"
        ),
    )
    with op.batch_alter_table("framework_versions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_framework_versions_framework_id"), ["framework_id"], unique=False
        )

    op.create_table(
        "status_definitions",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("scope", sa.String(length=24), nullable=False),
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("color_token", sa.String(length=40), nullable=False),
        sa.Column("icon", sa.String(length=40), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_terminal", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_status_definitions_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_status_definitions")),
        sa.UniqueConstraint("workspace_id", "code", name="uq_status_definition_workspace_code"),
    )
    with op.batch_alter_table("status_definitions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_status_definitions_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "tags",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_tags_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tags")),
        sa.UniqueConstraint("workspace_id", "name", name="uq_tag_workspace_name"),
    )
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tags_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "users",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("normalized_email", sa.String(length=320), nullable=True),
        sa.Column("display_name", sa.String(length=160), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("can_login", sa.Boolean(), nullable=False),
        sa.Column("is_disabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("role IN ('ADMIN', 'EDITOR', 'VIEWER')", name=op.f("user_role")),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_users_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("workspace_id", "normalized_email", name="uq_user_workspace_email"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_workspace_id"), ["workspace_id"], unique=False)

    op.create_table(
        "activity_events",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("action_code", sa.String(length=120), nullable=False),
        sa.Column("before_snapshot", sa.JSON(), nullable=True),
        sa.Column("after_snapshot", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_activity_events_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_activity_events_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activity_events")),
    )
    with op.batch_alter_table("activity_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_activity_events_action_code"), ["action_code"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_activity_events_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_activity_events_entity_type"), ["entity_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_activity_events_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "framework_domains",
        sa.Column("framework_version_id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("external_id", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=240), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["framework_version_id"],
            ["framework_versions.id"],
            name=op.f("fk_framework_domains_framework_version_id_framework_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["framework_domains.id"],
            name=op.f("fk_framework_domains_parent_id_framework_domains"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_framework_domains")),
        sa.UniqueConstraint(
            "framework_version_id", "external_id", name="uq_framework_domain_version_external_id"
        ),
    )
    with op.batch_alter_table("framework_domains", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_framework_domains_framework_version_id"),
            ["framework_version_id"],
            unique=False,
        )

    op.create_table(
        "organizational_controls",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=240), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status_code", sa.String(length=40), nullable=False),
        sa.Column("owner_user_id", sa.Uuid(), nullable=True),
        sa.Column("implementation_notes", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_organizational_controls_owner_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "status_code"],
            ["status_definitions.workspace_id", "status_definitions.code"],
            name="fk_control_workspace_status",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_organizational_controls_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizational_controls")),
        sa.UniqueConstraint("workspace_id", "code", name="uq_control_workspace_code"),
    )
    with op.batch_alter_table("organizational_controls", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_organizational_controls_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "sessions",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("secret_hash", sa.String(length=64), nullable=False),
        sa.Column("csrf_secret", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_sessions_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
        sa.UniqueConstraint("secret_hash", name="uq_session_secret_hash"),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sessions_user_id"), ["user_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_sessions_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "stored_files",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("storage_key", sa.String(length=240), nullable=False),
        sa.Column("original_filename", sa.String(length=500), nullable=False),
        sa.Column("normalized_extension", sa.String(length=20), nullable=False),
        sa.Column("declared_media_type", sa.String(length=200), nullable=False),
        sa.Column("detected_media_type", sa.String(length=200), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("uploaded_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["uploaded_by_user_id"],
            ["users.id"],
            name=op.f("fk_stored_files_uploaded_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_stored_files_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stored_files")),
        sa.UniqueConstraint("workspace_id", "sha256", name="uq_stored_file_workspace_sha256"),
        sa.UniqueConstraint("workspace_id", "storage_key", name="uq_stored_file_workspace_key"),
    )
    with op.batch_alter_table("stored_files", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_stored_files_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "control_tags",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("control_id", sa.Uuid(), nullable=False),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["control_id"],
            ["organizational_controls.id"],
            name=op.f("fk_control_tags_control_id_organizational_controls"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tags.id"], name=op.f("fk_control_tags_tag_id_tags"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_control_tags_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "workspace_id", "control_id", "tag_id", name=op.f("pk_control_tags")
        ),
        sa.UniqueConstraint("control_id", "tag_id", name="uq_control_tag_pair"),
    )
    op.create_table(
        "documents",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("stored_file_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("document_type", sa.String(length=24), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("version", sa.String(length=80), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.Column("owner_user_id", sa.Uuid(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "document_type IN ('POLICY', 'STANDARD', 'PROCEDURE', 'PLAN', 'GUIDELINE', 'OTHER')",
            name=op.f("ck_document_type"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_documents_owner_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["stored_file_id"],
            ["stored_files.id"],
            name=op.f("fk_documents_stored_file_id_stored_files"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_documents_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
    )
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_documents_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "evidence",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("stored_file_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("evidence_date", sa.Date(), nullable=True),
        sa.Column("owner_user_id", sa.Uuid(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_evidence_owner_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["stored_file_id"],
            ["stored_files.id"],
            name=op.f("fk_evidence_stored_file_id_stored_files"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_evidence_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evidence")),
    )
    with op.batch_alter_table("evidence", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_evidence_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "framework_requirements",
        sa.Column("framework_version_id", sa.Uuid(), nullable=False),
        sa.Column("domain_id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("external_id", sa.String(length=120), nullable=False),
        sa.Column("title", sa.String(length=400), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("guidance", sa.Text(), nullable=False),
        sa.Column("source_reference", sa.String(length=1000), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["domain_id"],
            ["framework_domains.id"],
            name=op.f("fk_framework_requirements_domain_id_framework_domains"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["framework_version_id"],
            ["framework_versions.id"],
            name=op.f("fk_framework_requirements_framework_version_id_framework_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["framework_requirements.id"],
            name=op.f("fk_framework_requirements_parent_id_framework_requirements"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_framework_requirements")),
        sa.UniqueConstraint(
            "framework_version_id",
            "external_id",
            name="uq_framework_requirement_version_external_id",
        ),
    )
    with op.batch_alter_table("framework_requirements", schema=None) as batch_op:
        batch_op.create_index(
            "ix_framework_requirement_domain_sort", ["domain_id", "sort_order"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_framework_requirements_domain_id"), ["domain_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_framework_requirements_framework_version_id"),
            ["framework_version_id"],
            unique=False,
        )

    op.create_table(
        "control_documents",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("control_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["control_id"],
            ["organizational_controls.id"],
            name=op.f("fk_control_documents_control_id_organizational_controls"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_control_documents_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_control_documents_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_control_documents")),
        sa.UniqueConstraint("control_id", "document_id", name="uq_control_document_pair"),
    )
    with op.batch_alter_table("control_documents", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_control_documents_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "control_evidence",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("control_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["control_id"],
            ["organizational_controls.id"],
            name=op.f("fk_control_evidence_control_id_organizational_controls"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidence.id"],
            name=op.f("fk_control_evidence_evidence_id_evidence"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_control_evidence_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_control_evidence")),
        sa.UniqueConstraint("control_id", "evidence_id", name="uq_control_evidence_pair"),
    )
    with op.batch_alter_table("control_evidence", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_control_evidence_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "requirement_assessments",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("requirement_id", sa.Uuid(), nullable=False),
        sa.Column("status_code", sa.String(length=40), nullable=False),
        sa.Column("applicability", sa.String(length=24), nullable=False),
        sa.Column("owner_user_id", sa.Uuid(), nullable=True),
        sa.Column("assignee_user_id", sa.Uuid(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("implementation_notes", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "applicability IN ('UNDETERMINED', 'APPLICABLE', 'NOT_APPLICABLE')",
            name=op.f("requirement_assessment_applicability"),
        ),
        sa.ForeignKeyConstraint(
            ["assignee_user_id"],
            ["users.id"],
            name=op.f("fk_requirement_assessments_assignee_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_requirement_assessments_owner_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["requirement_id"],
            ["framework_requirements.id"],
            name=op.f("fk_requirement_assessments_requirement_id_framework_requirements"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "status_code"],
            ["status_definitions.workspace_id", "status_definitions.code"],
            name="fk_requirement_assessment_workspace_status",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_requirement_assessments_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requirement_assessments")),
        sa.UniqueConstraint(
            "workspace_id", "requirement_id", name="uq_requirement_assessment_workspace_requirement"
        ),
    )
    with op.batch_alter_table("requirement_assessments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_requirement_assessments_requirement_id"),
            ["requirement_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_requirement_assessments_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "requirement_control_mappings",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("requirement_id", sa.Uuid(), nullable=False),
        sa.Column("control_id", sa.Uuid(), nullable=False),
        sa.Column("coverage", sa.String(length=24), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "coverage IN ('PRIMARY', 'SUPPORTING', 'LIMITED')",
            name=op.f("requirement_control_mapping_coverage"),
        ),
        sa.ForeignKeyConstraint(
            ["control_id"],
            ["organizational_controls.id"],
            name=op.f("fk_requirement_control_mappings_control_id_organizational_controls"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["requirement_id"],
            ["framework_requirements.id"],
            name=op.f("fk_requirement_control_mappings_requirement_id_framework_requirements"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_requirement_control_mappings_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requirement_control_mappings")),
        sa.UniqueConstraint(
            "workspace_id",
            "requirement_id",
            "control_id",
            name="uq_requirement_control_mapping_pair",
        ),
    )
    with op.batch_alter_table("requirement_control_mappings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_requirement_control_mappings_control_id"), ["control_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_requirement_control_mappings_requirement_id"),
            ["requirement_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_requirement_control_mappings_workspace_id"),
            ["workspace_id"],
            unique=False,
        )

    op.create_table(
        "requirement_documents",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("requirement_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_requirement_documents_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["requirement_id"],
            ["framework_requirements.id"],
            name=op.f("fk_requirement_documents_requirement_id_framework_requirements"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_requirement_documents_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requirement_documents")),
        sa.UniqueConstraint("requirement_id", "document_id", name="uq_requirement_document_pair"),
    )
    with op.batch_alter_table("requirement_documents", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_requirement_documents_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "requirement_evidence",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("requirement_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidence.id"],
            name=op.f("fk_requirement_evidence_evidence_id_evidence"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["requirement_id"],
            ["framework_requirements.id"],
            name=op.f("fk_requirement_evidence_requirement_id_framework_requirements"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_requirement_evidence_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requirement_evidence")),
        sa.UniqueConstraint("requirement_id", "evidence_id", name="uq_requirement_evidence_pair"),
    )
    with op.batch_alter_table("requirement_evidence", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_requirement_evidence_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "requirement_mappings",
        sa.Column("workspace_id", sa.Uuid(), nullable=True),
        sa.Column("source_requirement_id", sa.Uuid(), nullable=False),
        sa.Column("target_requirement_id", sa.Uuid(), nullable=False),
        sa.Column("relationship_type", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Integer(), nullable=True),
        sa.Column("mapping_source", sa.String(length=400), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "relationship_type IN ('EQUIVALENT', 'STRONG_OVERLAP', 'PARTIAL_OVERLAP', 'RELATED')",
            name=op.f("ck_requirement_mapping_relationship_type"),
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 100)",
            name=op.f("ck_requirement_mapping_confidence"),
        ),
        sa.CheckConstraint(
            "source_requirement_id <> target_requirement_id",
            name=op.f("ck_requirement_mapping_distinct"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_requirement_mappings_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_requirement_id"],
            ["framework_requirements.id"],
            name=op.f("fk_requirement_mappings_source_requirement_id_framework_requirements"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["target_requirement_id"],
            ["framework_requirements.id"],
            name=op.f("fk_requirement_mappings_target_requirement_id_framework_requirements"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_requirement_mappings_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requirement_mappings")),
        sa.UniqueConstraint(
            "source_requirement_id",
            "target_requirement_id",
            "relationship_type",
            name="uq_requirement_mapping_direction_type",
        ),
    )
    with op.batch_alter_table("requirement_mappings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_requirement_mappings_source_requirement_id"),
            ["source_requirement_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_requirement_mappings_target_requirement_id"),
            ["target_requirement_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_requirement_mappings_workspace_id"), ["workspace_id"], unique=False
        )

    op.create_table(
        "assessment_tags",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("assessment_id", sa.Uuid(), nullable=False),
        sa.Column("tag_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["requirement_assessments.id"],
            name=op.f("fk_assessment_tags_assessment_id_requirement_assessments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"], ["tags.id"], name=op.f("fk_assessment_tags_tag_id_tags"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_assessment_tags_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "workspace_id", "assessment_id", "tag_id", name=op.f("pk_assessment_tags")
        ),
        sa.UniqueConstraint("assessment_id", "tag_id", name="uq_assessment_tag_pair"),
    )
    op.create_table(
        "requirement_notes",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("assessment_id", sa.Uuid(), nullable=False),
        sa.Column("author_user_id", sa.Uuid(), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("edited_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["requirement_assessments.id"],
            name=op.f("fk_requirement_notes_assessment_id_requirement_assessments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["author_user_id"],
            ["users.id"],
            name=op.f("fk_requirement_notes_author_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_requirement_notes_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requirement_notes")),
    )
    with op.batch_alter_table("requirement_notes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_requirement_notes_assessment_id"), ["assessment_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_requirement_notes_workspace_id"), ["workspace_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("requirement_notes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_requirement_notes_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_requirement_notes_assessment_id"))

    op.drop_table("requirement_notes")
    op.drop_table("assessment_tags")
    with op.batch_alter_table("requirement_mappings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_requirement_mappings_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_requirement_mappings_target_requirement_id"))
        batch_op.drop_index(batch_op.f("ix_requirement_mappings_source_requirement_id"))

    op.drop_table("requirement_mappings")
    with op.batch_alter_table("requirement_evidence", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_requirement_evidence_workspace_id"))

    op.drop_table("requirement_evidence")
    with op.batch_alter_table("requirement_documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_requirement_documents_workspace_id"))

    op.drop_table("requirement_documents")
    with op.batch_alter_table("requirement_control_mappings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_requirement_control_mappings_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_requirement_control_mappings_requirement_id"))
        batch_op.drop_index(batch_op.f("ix_requirement_control_mappings_control_id"))

    op.drop_table("requirement_control_mappings")
    with op.batch_alter_table("requirement_assessments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_requirement_assessments_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_requirement_assessments_requirement_id"))

    op.drop_table("requirement_assessments")
    with op.batch_alter_table("control_evidence", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_control_evidence_workspace_id"))

    op.drop_table("control_evidence")
    with op.batch_alter_table("control_documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_control_documents_workspace_id"))

    op.drop_table("control_documents")
    with op.batch_alter_table("framework_requirements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_framework_requirements_framework_version_id"))
        batch_op.drop_index(batch_op.f("ix_framework_requirements_domain_id"))
        batch_op.drop_index("ix_framework_requirement_domain_sort")

    op.drop_table("framework_requirements")
    with op.batch_alter_table("evidence", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_evidence_workspace_id"))

    op.drop_table("evidence")
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_documents_workspace_id"))

    op.drop_table("documents")
    op.drop_table("control_tags")
    with op.batch_alter_table("stored_files", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_stored_files_workspace_id"))

    op.drop_table("stored_files")
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sessions_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_sessions_user_id"))

    op.drop_table("sessions")
    with op.batch_alter_table("organizational_controls", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_organizational_controls_workspace_id"))

    op.drop_table("organizational_controls")
    with op.batch_alter_table("framework_domains", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_framework_domains_framework_version_id"))

    op.drop_table("framework_domains")
    with op.batch_alter_table("activity_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_activity_events_workspace_id"))
        batch_op.drop_index(batch_op.f("ix_activity_events_entity_type"))
        batch_op.drop_index(batch_op.f("ix_activity_events_created_at"))
        batch_op.drop_index(batch_op.f("ix_activity_events_action_code"))

    op.drop_table("activity_events")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_workspace_id"))

    op.drop_table("users")
    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tags_workspace_id"))

    op.drop_table("tags")
    with op.batch_alter_table("status_definitions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_status_definitions_workspace_id"))

    op.drop_table("status_definitions")
    with op.batch_alter_table("framework_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_framework_versions_framework_id"))

    op.drop_table("framework_versions")
    op.drop_table("workspaces")
    op.drop_table("frameworks")
    # ### end Alembic commands ###
